trigger:
  branches:
    include:
      - '*'
  paths:
    exclude:
      - docs/*

pool:
  vmImage: 'ubuntu-20.04'
  demands:
  - npm

variables:
  CONFIGURATION: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK 6.x'
  inputs:
    packageType: sdk
    version: '6.x'

- script: 'npm run setup:ci'
  displayName: 'npm setup:ci'

- script: 'npm ci'
  displayName: 'npm ci'

- script: 'npm run sass'
  displayName: 'node-sass'

- task: gulp@1
  displayName: 'gulp'
  inputs:
    verbose: true

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'buildinfo.txt'
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- template: azure/pipelines/dotnet.yml
  parameters:
    CONFIGURATION: 'Debug'

- template: azure/pipelines/dotnet.yml
  parameters:
    CONFIGURATION: 'Release'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: $(Build.ArtifactStagingDirectory)'
  condition: succeeded()
